import type {
  Plate,
  Annotation,
  ReviewRecord,
  HistoryEntry,
  User,
  FilterOptions,
  DetectionResult,
  ModificationRecord,
} from '../types';
import { MOCK_USERS } from '../types';
import { v4 as uuidv4 } from 'uuid';

const defaultUser = MOCK_USERS[0];

const MOCK_PLATES: Plate[] = [
  {
    id: 'plate-1',
    code: 'AP-001',
    name: '猎户座天区底片',
    scanDate: '2024-03-15',
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'active',
    description: '1978年拍摄的猎户座天区玻璃底片',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'plate-2',
    code: 'AP-002',
    name: '仙女座大星云底片',
    scanDate: '2024-02-20',
    imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'active',
    description: '1985年拍摄的仙女座大星云底片',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'plate-3',
    code: 'AP-003',
    name: '银河中心区域底片',
    scanDate: '2024-01-10',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'archived',
    description: '1990年拍摄的银河系中心区域底片',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

const MOCK_ANNOTATIONS: Annotation[] = [
  {
    id: 'ann-1',
    plateId: 'plate-1',
    shape: 'rectangle',
    x: 100,
    y: 150,
    width: 80,
    height: 60,
    defectType: 'scratch',
    severity: 'moderate',
    description: '底片左上角有一条明显的划痕',
    suggestion: '使用数字修复技术进行修复',
    reviewStatus: 'reviewed',
    createdBy: 'user-1',
    createdByName: '张标注',
    createdAt: '2024-03-16T09:30:00Z',
    updatedAt: '2024-03-16T14:00:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 0.92,
    isAutoDetected: true,
    autoDetectType: 'scratch',
    autoConfidence: 0.85,
    modificationReason: 'incorrect_boundary',
    modificationNote: '调整了划痕边界框，使其更准确',
  },
  {
    id: 'ann-2',
    plateId: 'plate-1',
    shape: 'circle',
    x: 300,
    y: 200,
    radius: 25,
    defectType: 'mold',
    severity: 'severe',
    description: '中央区域有大片霉斑，影响星体观测',
    suggestion: '需要专业清洗和防霉处理，严重区域可能需要数字化修复',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:15:00Z',
    updatedAt: '2024-03-16T10:15:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.78,
    isAutoDetected: true,
    autoDetectType: 'mold',
    autoConfidence: 0.78,
  },
  {
    id: 'ann-3',
    plateId: 'plate-1',
    shape: 'polygon',
    points: [
      { x: 500, y: 100 },
      { x: 550, y: 120 },
      { x: 540, y: 180 },
      { x: 490, y: 170 },
    ],
    defectType: 'bright_spot',
    severity: 'mild',
    description: '扫描时产生的亮点污染',
    suggestion: '',
    reviewStatus: 'rejected',
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-03-17T08:00:00Z',
    updatedAt: '2024-03-17T11:30:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 0.45,
    isAutoDetected: true,
    autoDetectType: 'bright_spot',
    autoConfidence: 0.62,
    modificationReason: 'false_positive',
    modificationNote: '复核确认是真实星体，非亮点污染',
  },
  {
    id: 'ann-4',
    plateId: 'plate-2',
    shape: 'rectangle',
    x: 150,
    y: 180,
    width: 100,
    height: 50,
    defectType: 'scan_defect',
    severity: 'moderate',
    description: '扫描过程中产生的横向条纹',
    suggestion: '使用图像处理软件去除扫描条纹',
    reviewStatus: 'reviewed',
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-02-25T14:20:00Z',
    updatedAt: '2024-02-26T09:00:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 1.0,
    isAutoDetected: false,
  },
  {
    id: 'ann-5',
    plateId: 'plate-1',
    shape: 'rectangle',
    x: 450,
    y: 300,
    width: 60,
    height: 40,
    defectType: 'scratch',
    severity: 'mild',
    description: '底部细小划痕',
    suggestion: '',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:20:00Z',
    updatedAt: '2024-03-16T10:20:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.95,
    isAutoDetected: true,
    autoDetectType: 'scratch',
    autoConfidence: 0.95,
  },
  {
    id: 'ann-6',
    plateId: 'plate-1',
    shape: 'circle',
    x: 200,
    y: 350,
    radius: 15,
    defectType: 'mold',
    severity: 'moderate',
    description: '左下角小面积霉斑',
    suggestion: '',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:22:00Z',
    updatedAt: '2024-03-16T10:22:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.68,
    isAutoDetected: true,
    autoDetectType: 'mold',
    autoConfidence: 0.68,
  },
  {
    id: 'ann-7',
    plateId: 'plate-2',
    shape: 'rectangle',
    x: 400,
    y: 250,
    width: 120,
    height: 30,
    defectType: 'scan_defect',
    severity: 'severe',
    description: '大片扫描条纹区域',
    suggestion: '需要进行频域滤波处理',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-02-25T14:25:00Z',
    updatedAt: '2024-02-25T14:25:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.88,
    isAutoDetected: true,
    autoDetectType: 'scan_defect',
    autoConfidence: 0.88,
  },
];

const MOCK_REVIEW_RECORDS: ReviewRecord[] = [
  {
    id: 'review-1',
    annotationId: 'ann-1',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'reviewed',
    comment: '标注准确，建议合理，通过复核。',
    reviewedAt: '2024-03-16T14:00:00Z',
  },
  {
    id: 'review-2',
    annotationId: 'ann-3',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'rejected',
    comment: '该亮点为真实星体，非扫描污染，请重新确认。',
    reviewedAt: '2024-03-17T11:30:00Z',
  },
  {
    id: 'review-3',
    annotationId: 'ann-4',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'reviewed',
    comment: '扫描缺陷标注正确，处理建议可行。',
    reviewedAt: '2024-02-26T09:00:00Z',
  },
];

const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: 'hist-1',
    annotationId: 'ann-1',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T09:30:00Z',
    description: '创建划痕标注',
  },
  {
    id: 'hist-2',
    annotationId: 'ann-1',
    action: 'update',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T10:00:00Z',
    beforeData: { description: '' },
    afterData: { description: '底片左上角有一条明显的划痕' },
    description: '更新缺陷描述',
  },
  {
    id: 'hist-3',
    annotationId: 'ann-1',
    action: 'review',
    userId: 'user-2',
    userName: '李复核',
    timestamp: '2024-03-16T14:00:00Z',
    beforeData: { reviewStatus: 'pending' },
    afterData: { reviewStatus: 'reviewed' },
    description: '复核通过',
  },
  {
    id: 'hist-4',
    annotationId: 'ann-2',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T10:15:00Z',
    description: '创建霉斑标注',
  },
  {
    id: 'hist-5',
    annotationId: 'ann-3',
    action: 'create',
    userId: 'user-4',
    userName: '赵标注',
    timestamp: '2024-03-17T08:00:00Z',
    description: '创建亮点污染标注',
  },
  {
    id: 'hist-6',
    annotationId: 'ann-3',
    action: 'review',
    userId: 'user-2',
    userName: '李复核',
    timestamp: '2024-03-17T11:30:00Z',
    beforeData: { reviewStatus: 'pending' },
    afterData: { reviewStatus: 'rejected' },
    description: '复核驳回',
  },
];

const MOCK_DETECTION_RESULTS: DetectionResult[] = [
  {
    plateId: 'plate-1',
    status: 'completed',
    progress: 100,
    totalDetected: 5,
    startedAt: '2024-03-16T09:00:00Z',
    completedAt: '2024-03-16T09:02:30Z',
  },
  {
    plateId: 'plate-2',
    status: 'completed',
    progress: 100,
    totalDetected: 2,
    startedAt: '2024-02-25T14:00:00Z',
    completedAt: '2024-02-25T14:01:45Z',
  },
];

const MOCK_MODIFICATION_RECORDS: ModificationRecord[] = [
  {
    id: 'mod-1',
    annotationId: 'ann-1',
    reason: 'incorrect_boundary',
    description: '调整了划痕边界框，使其更准确地覆盖缺陷区域',
    modifiedBy: 'user-1',
    modifiedByName: '张标注',
    modifiedAt: '2024-03-16T10:00:00Z',
  },
  {
    id: 'mod-2',
    annotationId: 'ann-3',
    reason: 'false_positive',
    description: '复核确认是真实星体，非亮点污染，标记为误检',
    modifiedBy: 'user-2',
    modifiedByName: '李复核',
    modifiedAt: '2024-03-17T11:30:00Z',
  },
];

export const DEFAULT_FILTERS: FilterOptions = {
  defectTypes: [],
  severities: [],
  reviewStatuses: [],
  keyword: '',
  confidenceMin: undefined,
  confidenceMax: undefined,
  isAutoDetected: null,
};

export const initialState: State = {
  currentUser: defaultUser,
  plates: MOCK_PLATES,
  annotations: MOCK_ANNOTATIONS,
  reviewRecords: MOCK_REVIEW_RECORDS,
  history: MOCK_HISTORY,
  detectionResults: MOCK_DETECTION_RESULTS,
  modificationRecords: MOCK_MODIFICATION_RECORDS,
  selectedPlateId: MOCK_PLATES[0]?.id || null,
  selectedAnnotationId: null,
  selectedAnnotationIds: [],
  filters: DEFAULT_FILTERS,
  historyUndoStack: [],
  historyRedoStack: [],
  confidenceThreshold: 0.5,
};

export interface State {
  currentUser: User;
  plates: Plate[];
  annotations: Annotation[];
  reviewRecords: ReviewRecord[];
  history: HistoryEntry[];
  detectionResults: DetectionResult[];
  modificationRecords: ModificationRecord[];
  selectedPlateId: string | null;
  selectedAnnotationId: string | null;
  selectedAnnotationIds: string[];
  filters: FilterOptions;
  historyUndoStack: HistoryEntry[][];
  historyRedoStack: HistoryEntry[][];
  confidenceThreshold: number;
}
