import type {
  Plate,
  Annotation,
  ReviewRecord,
  HistoryEntry,
  User,
  FilterOptions,
  DetectionResult,
  ModificationRecord,
  PlateVersion,
  ComparisonResult,
  ApprovalRecord,
  VersionChangeHistory,
  FinalConclusion,
  TrendStatistics,
} from '../types';
import { MOCK_USERS } from '../types';
import { v4 as uuidv4 } from 'uuid';
import { compareAnnotations } from '../services/comparisonService';

const defaultUser = MOCK_USERS[0];

const MOCK_PLATES: Plate[] = [
  {
    id: 'plate-1',
    code: 'AP-001',
    name: '猎户座天区底片',
    scanDate: '2024-03-15',
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'active',
    description: '1978年拍摄的猎户座天区玻璃底片',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
  },
  {
    id: 'plate-2',
    code: 'AP-002',
    name: '仙女座大星云底片',
    scanDate: '2024-02-20',
    imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'active',
    description: '1985年拍摄的仙女座大星云底片',
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'plate-3',
    code: 'AP-003',
    name: '银河中心区域底片',
    scanDate: '2024-01-10',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=200&q=80',
    width: 1200,
    height: 900,
    status: 'archived',
    description: '1990年拍摄的银河系中心区域底片',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

const MOCK_ANNOTATIONS: Annotation[] = [
  {
    id: 'ann-1',
    plateId: 'plate-1',
    shape: 'rectangle',
    x: 100,
    y: 150,
    width: 80,
    height: 60,
    defectType: 'scratch',
    severity: 'moderate',
    description: '底片左上角有一条明显的划痕',
    suggestion: '使用数字修复技术进行修复',
    reviewStatus: 'reviewed',
    createdBy: 'user-1',
    createdByName: '张标注',
    createdAt: '2024-03-16T09:30:00Z',
    updatedAt: '2024-03-16T14:00:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 0.92,
    isAutoDetected: true,
    autoDetectType: 'scratch',
    autoConfidence: 0.85,
    modificationReason: 'incorrect_boundary',
    modificationNote: '调整了划痕边界框，使其更准确',
  },
  {
    id: 'ann-2',
    plateId: 'plate-1',
    shape: 'circle',
    x: 300,
    y: 200,
    radius: 25,
    defectType: 'mold',
    severity: 'severe',
    description: '中央区域有大片霉斑，影响星体观测',
    suggestion: '需要专业清洗和防霉处理，严重区域可能需要数字化修复',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:15:00Z',
    updatedAt: '2024-03-16T10:15:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.78,
    isAutoDetected: true,
    autoDetectType: 'mold',
    autoConfidence: 0.78,
  },
  {
    id: 'ann-3',
    plateId: 'plate-1',
    shape: 'polygon',
    points: [
      { x: 500, y: 100 },
      { x: 550, y: 120 },
      { x: 540, y: 180 },
      { x: 490, y: 170 },
    ],
    defectType: 'bright_spot',
    severity: 'mild',
    description: '扫描时产生的亮点污染',
    suggestion: '',
    reviewStatus: 'rejected',
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-03-17T08:00:00Z',
    updatedAt: '2024-03-17T11:30:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 0.45,
    isAutoDetected: true,
    autoDetectType: 'bright_spot',
    autoConfidence: 0.62,
    modificationReason: 'false_positive',
    modificationNote: '复核确认是真实星体，非亮点污染',
  },
  {
    id: 'ann-4',
    plateId: 'plate-2',
    shape: 'rectangle',
    x: 150,
    y: 180,
    width: 100,
    height: 50,
    defectType: 'scan_defect',
    severity: 'moderate',
    description: '扫描过程中产生的横向条纹',
    suggestion: '使用图像处理软件去除扫描条纹',
    reviewStatus: 'reviewed',
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-02-25T14:20:00Z',
    updatedAt: '2024-02-26T09:00:00Z',
    lastModifiedBy: 'user-2',
    lastModifiedByName: '李复核',
    confidence: 1.0,
    isAutoDetected: false,
  },
  {
    id: 'ann-5',
    plateId: 'plate-1',
    shape: 'rectangle',
    x: 450,
    y: 300,
    width: 60,
    height: 40,
    defectType: 'scratch',
    severity: 'mild',
    description: '底部细小划痕',
    suggestion: '',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:20:00Z',
    updatedAt: '2024-03-16T10:20:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.95,
    isAutoDetected: true,
    autoDetectType: 'scratch',
    autoConfidence: 0.95,
  },
  {
    id: 'ann-6',
    plateId: 'plate-1',
    shape: 'circle',
    x: 200,
    y: 350,
    radius: 15,
    defectType: 'mold',
    severity: 'moderate',
    description: '左下角小面积霉斑',
    suggestion: '',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-03-16T10:22:00Z',
    updatedAt: '2024-03-16T10:22:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.68,
    isAutoDetected: true,
    autoDetectType: 'mold',
    autoConfidence: 0.68,
  },
  {
    id: 'ann-7',
    plateId: 'plate-2',
    shape: 'rectangle',
    x: 400,
    y: 250,
    width: 120,
    height: 30,
    defectType: 'scan_defect',
    severity: 'severe',
    description: '大片扫描条纹区域',
    suggestion: '需要进行频域滤波处理',
    reviewStatus: 'pending',
    createdBy: 'ai-system',
    createdByName: 'AI自动检测',
    createdAt: '2024-02-25T14:25:00Z',
    updatedAt: '2024-02-25T14:25:00Z',
    lastModifiedBy: 'ai-system',
    lastModifiedByName: 'AI自动检测',
    confidence: 0.88,
    isAutoDetected: true,
    autoDetectType: 'scan_defect',
    autoConfidence: 0.88,
  },
];

const MOCK_REVIEW_RECORDS: ReviewRecord[] = [
  {
    id: 'review-1',
    annotationId: 'ann-1',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'reviewed',
    comment: '标注准确，建议合理，通过复核。',
    reviewedAt: '2024-03-16T14:00:00Z',
  },
  {
    id: 'review-2',
    annotationId: 'ann-3',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'rejected',
    comment: '该亮点为真实星体，非扫描污染，请重新确认。',
    reviewedAt: '2024-03-17T11:30:00Z',
  },
  {
    id: 'review-3',
    annotationId: 'ann-4',
    reviewerId: 'user-2',
    reviewerName: '李复核',
    status: 'reviewed',
    comment: '扫描缺陷标注正确，处理建议可行。',
    reviewedAt: '2024-02-26T09:00:00Z',
  },
];

const MOCK_HISTORY: HistoryEntry[] = [
  {
    id: 'hist-1',
    annotationId: 'ann-1',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T09:30:00Z',
    description: '创建划痕标注',
  },
  {
    id: 'hist-2',
    annotationId: 'ann-1',
    action: 'update',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T10:00:00Z',
    beforeData: { description: '' },
    afterData: { description: '底片左上角有一条明显的划痕' },
    description: '更新缺陷描述',
  },
  {
    id: 'hist-3',
    annotationId: 'ann-1',
    action: 'review',
    userId: 'user-2',
    userName: '李复核',
    timestamp: '2024-03-16T14:00:00Z',
    beforeData: { reviewStatus: 'pending' },
    afterData: { reviewStatus: 'reviewed' },
    description: '复核通过',
  },
  {
    id: 'hist-4',
    annotationId: 'ann-2',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-03-16T10:15:00Z',
    description: '创建霉斑标注',
  },
  {
    id: 'hist-5',
    annotationId: 'ann-3',
    action: 'create',
    userId: 'user-4',
    userName: '赵标注',
    timestamp: '2024-03-17T08:00:00Z',
    description: '创建亮点污染标注',
  },
  {
    id: 'hist-6',
    annotationId: 'ann-3',
    action: 'review',
    userId: 'user-2',
    userName: '李复核',
    timestamp: '2024-03-17T11:30:00Z',
    beforeData: { reviewStatus: 'pending' },
    afterData: { reviewStatus: 'rejected' },
    description: '复核驳回',
  },
];

const MOCK_DETECTION_RESULTS: DetectionResult[] = [
  {
    plateId: 'plate-1',
    status: 'completed',
    progress: 100,
    totalDetected: 5,
    startedAt: '2024-03-16T09:00:00Z',
    completedAt: '2024-03-16T09:02:30Z',
  },
  {
    plateId: 'plate-2',
    status: 'completed',
    progress: 100,
    totalDetected: 2,
    startedAt: '2024-02-25T14:00:00Z',
    completedAt: '2024-02-25T14:01:45Z',
  },
];

const MOCK_MODIFICATION_RECORDS: ModificationRecord[] = [
  {
    id: 'mod-1',
    annotationId: 'ann-1',
    reason: 'incorrect_boundary',
    description: '调整了划痕边界框，使其更准确地覆盖缺陷区域',
    modifiedBy: 'user-1',
    modifiedByName: '张标注',
    modifiedAt: '2024-03-16T10:00:00Z',
  },
  {
    id: 'mod-2',
    annotationId: 'ann-3',
    reason: 'false_positive',
    description: '复核确认是真实星体，非亮点污染，标记为误检',
    modifiedBy: 'user-2',
    modifiedByName: '李复核',
    modifiedAt: '2024-03-17T11:30:00Z',
  },
];

export const DEFAULT_FILTERS: FilterOptions = {
  defectTypes: [],
  severities: [],
  reviewStatuses: [],
  keyword: '',
  confidenceMin: undefined,
  confidenceMax: undefined,
  isAutoDetected: null,
};

const MOCK_PLATE_VERSIONS: PlateVersion[] = [
  {
    id: 'version-1',
    plateId: 'plate-1',
    versionNumber: 1,
    versionName: '初始扫描版',
    scanDate: '2024-01-15',
    scanBatch: 'BATCH-2024-01',
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=200&q=80',
    width: 1200,
    height: 900,
    annotationCount: 4,
    createdBy: 'user-1',
    createdByName: '张标注',
    createdAt: '2024-01-15T10:00:00Z',
    description: '第一次扫描，基础版本',
    isBaseline: true,
  },
  {
    id: 'version-2',
    plateId: 'plate-1',
    versionNumber: 2,
    versionName: '二次扫描版',
    scanDate: '2024-03-15',
    scanBatch: 'BATCH-2024-03',
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=200&q=80',
    width: 1200,
    height: 900,
    annotationCount: 6,
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-03-15T14:30:00Z',
    description: '第二次扫描，新增了部分缺陷标注',
    isBaseline: false,
  },
  {
    id: 'version-3',
    plateId: 'plate-1',
    versionNumber: 3,
    versionName: '高清重扫版',
    scanDate: '2024-06-20',
    scanBatch: 'BATCH-2024-06-HD',
    imageUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=200&q=80',
    width: 1200,
    height: 900,
    annotationCount: 7,
    createdBy: 'user-1',
    createdByName: '张标注',
    createdAt: '2024-06-20T09:00:00Z',
    description: '高清扫描仪重新扫描，部分缺陷位置有微调',
    isBaseline: false,
  },
  {
    id: 'version-4',
    plateId: 'plate-2',
    versionNumber: 1,
    versionName: '初始扫描版',
    scanDate: '2024-02-20',
    scanBatch: 'BATCH-2024-02',
    imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=200&q=80',
    width: 1200,
    height: 900,
    annotationCount: 2,
    createdBy: 'user-4',
    createdByName: '赵标注',
    createdAt: '2024-02-20T10:00:00Z',
    description: '仙女座星云底片初始版本',
    isBaseline: true,
  },
  {
    id: 'version-5',
    plateId: 'plate-2',
    versionNumber: 2,
    versionName: '复核扫描版',
    scanDate: '2024-05-10',
    scanBatch: 'BATCH-2024-05',
    imageUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506443432602-ac2fcd6f54e0?w=200&q=80',
    width: 1200,
    height: 900,
    annotationCount: 3,
    createdBy: 'user-1',
    createdByName: '张标注',
    createdAt: '2024-05-10T11:00:00Z',
    description: '复核时重新扫描，新增一处扫描缺陷',
    isBaseline: false,
  },
];

const generateVersionAnnotations = (versionId: string, baseAnns: Annotation[]): Annotation[] => {
  return baseAnns.map((ann, index) => ({
    ...ann,
    id: `${versionId}-ann-${index + 1}`,
  }));
};

const MOCK_VERSION_ANNOTATIONS: Record<string, Annotation[]> = {
  'version-1': [
    {
      id: 'v1-ann-1',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 100,
      y: 150,
      width: 80,
      height: 60,
      defectType: 'scratch',
      severity: 'moderate',
      description: '底片左上角有一条明显的划痕',
      suggestion: '使用数字修复技术进行修复',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-01-15T09:30:00Z',
      updatedAt: '2024-01-15T14:00:00Z',
      lastModifiedBy: 'user-2',
      lastModifiedByName: '李复核',
      confidence: 0.88,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.82,
    },
    {
      id: 'v1-ann-2',
      plateId: 'plate-1',
      shape: 'circle',
      x: 300,
      y: 200,
      radius: 25,
      defectType: 'mold',
      severity: 'severe',
      description: '中央区域有霉斑',
      suggestion: '需要专业清洗',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-01-15T10:15:00Z',
      updatedAt: '2024-01-15T10:15:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.72,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.72,
    },
    {
      id: 'v1-ann-3',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 450,
      y: 300,
      width: 60,
      height: 40,
      defectType: 'scratch',
      severity: 'mild',
      description: '底部细小划痕',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-01-15T10:20:00Z',
      updatedAt: '2024-01-15T10:20:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.90,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.90,
    },
    {
      id: 'v1-ann-4',
      plateId: 'plate-1',
      shape: 'circle',
      x: 200,
      y: 350,
      radius: 15,
      defectType: 'mold',
      severity: 'moderate',
      description: '左下角小面积霉斑',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-01-15T10:22:00Z',
      updatedAt: '2024-01-15T10:22:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.65,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.65,
    },
  ],
  'version-2': [
    {
      id: 'v2-ann-1',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 105,
      y: 152,
      width: 82,
      height: 58,
      defectType: 'scratch',
      severity: 'moderate',
      description: '底片左上角有一条明显的划痕',
      suggestion: '使用数字修复技术进行修复',
      reviewStatus: 'reviewed',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-15T09:30:00Z',
      updatedAt: '2024-03-15T14:00:00Z',
      lastModifiedBy: 'user-2',
      lastModifiedByName: '李复核',
      confidence: 0.92,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.85,
    },
    {
      id: 'v2-ann-2',
      plateId: 'plate-1',
      shape: 'circle',
      x: 305,
      y: 198,
      radius: 28,
      defectType: 'mold',
      severity: 'severe',
      description: '中央区域有大片霉斑，影响星体观测',
      suggestion: '需要专业清洗和防霉处理，严重区域可能需要数字化修复',
      reviewStatus: 'pending',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-15T10:15:00Z',
      updatedAt: '2024-03-15T10:15:00Z',
      lastModifiedBy: 'user-4',
      lastModifiedByName: '赵标注',
      confidence: 0.78,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.78,
    },
    {
      id: 'v2-ann-3',
      plateId: 'plate-1',
      shape: 'polygon',
      points: [
        { x: 500, y: 100 },
        { x: 550, y: 120 },
        { x: 540, y: 180 },
        { x: 490, y: 170 },
      ],
      defectType: 'bright_spot',
      severity: 'mild',
      description: '扫描时产生的亮点污染',
      suggestion: '',
      reviewStatus: 'rejected',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-17T08:00:00Z',
      updatedAt: '2024-03-17T11:30:00Z',
      lastModifiedBy: 'user-2',
      lastModifiedByName: '李复核',
      confidence: 0.45,
      isAutoDetected: true,
      autoDetectType: 'bright_spot',
      autoConfidence: 0.62,
      modificationReason: 'false_positive',
      modificationNote: '复核确认是真实星体，非亮点污染',
    },
    {
      id: 'v2-ann-4',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 455,
      y: 298,
      width: 58,
      height: 42,
      defectType: 'scratch',
      severity: 'mild',
      description: '底部细小划痕',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-15T10:20:00Z',
      updatedAt: '2024-03-15T10:20:00Z',
      lastModifiedBy: 'user-4',
      lastModifiedByName: '赵标注',
      confidence: 0.95,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.95,
    },
    {
      id: 'v2-ann-5',
      plateId: 'plate-1',
      shape: 'circle',
      x: 195,
      y: 355,
      radius: 16,
      defectType: 'mold',
      severity: 'moderate',
      description: '左下角小面积霉斑',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-15T10:22:00Z',
      updatedAt: '2024-03-15T10:22:00Z',
      lastModifiedBy: 'user-4',
      lastModifiedByName: '赵标注',
      confidence: 0.68,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.68,
    },
    {
      id: 'v2-ann-6',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 600,
      y: 400,
      width: 70,
      height: 30,
      defectType: 'scan_defect',
      severity: 'moderate',
      description: '新增扫描条纹缺陷',
      suggestion: '使用频域滤波去除',
      reviewStatus: 'pending',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-03-15T11:00:00Z',
      updatedAt: '2024-03-15T11:00:00Z',
      lastModifiedBy: 'user-4',
      lastModifiedByName: '赵标注',
      confidence: 0.82,
      isAutoDetected: true,
      autoDetectType: 'scan_defect',
      autoConfidence: 0.82,
    },
  ],
  'version-3': [
    {
      id: 'v3-ann-1',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 102,
      y: 148,
      width: 85,
      height: 62,
      defectType: 'scratch',
      severity: 'moderate',
      description: '底片左上角有一条明显的划痕',
      suggestion: '使用数字修复技术进行修复',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T09:00:00Z',
      updatedAt: '2024-06-20T14:00:00Z',
      lastModifiedBy: 'user-5',
      lastModifiedByName: '陈研究员',
      confidence: 0.94,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.88,
      modificationReason: 'incorrect_boundary',
      modificationNote: '高清扫描后调整了边界',
    },
    {
      id: 'v3-ann-2',
      plateId: 'plate-1',
      shape: 'circle',
      x: 308,
      y: 195,
      radius: 32,
      defectType: 'mold',
      severity: 'severe',
      description: '中央区域有大片霉斑，影响星体观测',
      suggestion: '需要专业清洗和防霉处理，严重区域可能需要数字化修复',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T10:15:00Z',
      updatedAt: '2024-06-20T15:00:00Z',
      lastModifiedBy: 'user-5',
      lastModifiedByName: '陈研究员',
      confidence: 0.85,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.80,
    },
    {
      id: 'v3-ann-3',
      plateId: 'plate-1',
      shape: 'polygon',
      points: [
        { x: 505, y: 95 },
        { x: 555, y: 115 },
        { x: 545, y: 175 },
        { x: 495, y: 165 },
      ],
      defectType: 'bright_spot',
      severity: 'mild',
      description: '扫描时产生的亮点污染',
      suggestion: '',
      reviewStatus: 'rejected',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T08:00:00Z',
      updatedAt: '2024-06-20T11:30:00Z',
      lastModifiedBy: 'user-5',
      lastModifiedByName: '陈研究员',
      confidence: 0.42,
      isAutoDetected: true,
      autoDetectType: 'bright_spot',
      autoConfidence: 0.58,
      modificationReason: 'false_positive',
      modificationNote: '确认是真实星体',
    },
    {
      id: 'v3-ann-4',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 452,
      y: 302,
      width: 62,
      height: 38,
      defectType: 'scratch',
      severity: 'mild',
      description: '底部细小划痕',
      suggestion: '',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T10:20:00Z',
      updatedAt: '2024-06-20T10:20:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.96,
      isAutoDetected: true,
      autoDetectType: 'scratch',
      autoConfidence: 0.96,
    },
    {
      id: 'v3-ann-5',
      plateId: 'plate-1',
      shape: 'circle',
      x: 198,
      y: 352,
      radius: 18,
      defectType: 'mold',
      severity: 'moderate',
      description: '左下角小面积霉斑，范围略有扩大',
      suggestion: '建议进行防霉处理',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T10:22:00Z',
      updatedAt: '2024-06-20T10:22:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.72,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.72,
    },
    {
      id: 'v3-ann-6',
      plateId: 'plate-1',
      shape: 'rectangle',
      x: 605,
      y: 398,
      width: 75,
      height: 32,
      defectType: 'scan_defect',
      severity: 'moderate',
      description: '扫描条纹缺陷',
      suggestion: '使用频域滤波去除',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T11:00:00Z',
      updatedAt: '2024-06-20T11:00:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.88,
      isAutoDetected: true,
      autoDetectType: 'scan_defect',
      autoConfidence: 0.88,
    },
    {
      id: 'v3-ann-7',
      plateId: 'plate-1',
      shape: 'circle',
      x: 700,
      y: 250,
      radius: 20,
      defectType: 'mold',
      severity: 'mild',
      description: '右侧新发现的小霉斑',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-06-20T13:00:00Z',
      updatedAt: '2024-06-20T13:00:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.55,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.55,
    },
  ],
  'version-4': [
    {
      id: 'v4-ann-1',
      plateId: 'plate-2',
      shape: 'rectangle',
      x: 150,
      y: 180,
      width: 100,
      height: 50,
      defectType: 'scan_defect',
      severity: 'moderate',
      description: '扫描过程中产生的横向条纹',
      suggestion: '使用图像处理软件去除扫描条纹',
      reviewStatus: 'reviewed',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-02-20T14:20:00Z',
      updatedAt: '2024-02-21T09:00:00Z',
      lastModifiedBy: 'user-2',
      lastModifiedByName: '李复核',
      confidence: 1.0,
      isAutoDetected: false,
    },
    {
      id: 'v4-ann-2',
      plateId: 'plate-2',
      shape: 'rectangle',
      x: 400,
      y: 250,
      width: 120,
      height: 30,
      defectType: 'scan_defect',
      severity: 'severe',
      description: '大片扫描条纹区域',
      suggestion: '需要进行频域滤波处理',
      reviewStatus: 'pending',
      createdBy: 'user-4',
      createdByName: '赵标注',
      createdAt: '2024-02-20T14:25:00Z',
      updatedAt: '2024-02-20T14:25:00Z',
      lastModifiedBy: 'user-4',
      lastModifiedByName: '赵标注',
      confidence: 0.88,
      isAutoDetected: true,
      autoDetectType: 'scan_defect',
      autoConfidence: 0.88,
    },
  ],
  'version-5': [
    {
      id: 'v5-ann-1',
      plateId: 'plate-2',
      shape: 'rectangle',
      x: 148,
      y: 178,
      width: 105,
      height: 52,
      defectType: 'scan_defect',
      severity: 'moderate',
      description: '扫描过程中产生的横向条纹',
      suggestion: '使用图像处理软件去除扫描条纹',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-05-10T14:20:00Z',
      updatedAt: '2024-05-11T09:00:00Z',
      lastModifiedBy: 'user-5',
      lastModifiedByName: '陈研究员',
      confidence: 0.95,
      isAutoDetected: false,
    },
    {
      id: 'v5-ann-2',
      plateId: 'plate-2',
      shape: 'rectangle',
      x: 395,
      y: 248,
      width: 125,
      height: 32,
      defectType: 'scan_defect',
      severity: 'severe',
      description: '大片扫描条纹区域',
      suggestion: '需要进行频域滤波处理',
      reviewStatus: 'reviewed',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-05-10T14:25:00Z',
      updatedAt: '2024-05-11T09:00:00Z',
      lastModifiedBy: 'user-5',
      lastModifiedByName: '陈研究员',
      confidence: 0.92,
      isAutoDetected: true,
      autoDetectType: 'scan_defect',
      autoConfidence: 0.88,
    },
    {
      id: 'v5-ann-3',
      plateId: 'plate-2',
      shape: 'circle',
      x: 280,
      y: 350,
      radius: 22,
      defectType: 'mold',
      severity: 'mild',
      description: '右下角新发现的小霉斑',
      suggestion: '',
      reviewStatus: 'pending',
      createdBy: 'user-1',
      createdByName: '张标注',
      createdAt: '2024-05-10T15:30:00Z',
      updatedAt: '2024-05-10T15:30:00Z',
      lastModifiedBy: 'user-1',
      lastModifiedByName: '张标注',
      confidence: 0.62,
      isAutoDetected: true,
      autoDetectType: 'mold',
      autoConfidence: 0.62,
    },
  ],
};

const createInitialComparison = (): ComparisonResult => {
  return compareAnnotations(
    MOCK_VERSION_ANNOTATIONS['version-1'],
    MOCK_VERSION_ANNOTATIONS['version-2'],
    'plate-1',
    'version-1',
    'version-2',
    'user-2',
    '李复核'
  );
};

const MOCK_COMPARISONS: ComparisonResult[] = [
  createInitialComparison(),
];

const MOCK_APPROVAL_RECORDS: ApprovalRecord[] = [
  {
    id: 'approval-1',
    diffItemId: MOCK_COMPARISONS[0]?.diffItems[0]?.id || '',
    comparisonId: MOCK_COMPARISONS[0]?.id || '',
    approverId: 'user-2',
    approverName: '李复核',
    status: 'approved',
    comment: '确认该划痕位置有微调，属于正常扫描误差。',
    createdAt: '2024-03-16T10:00:00Z',
  },
  {
    id: 'approval-2',
    diffItemId: MOCK_COMPARISONS[0]?.diffItems.find((d) => d.diffType === 'added')?.id || '',
    comparisonId: MOCK_COMPARISONS[0]?.id || '',
    approverId: 'user-5',
    approverName: '陈研究员',
    status: 'pending',
    comment: '',
    createdAt: '2024-03-16T11:00:00Z',
  },
];

const MOCK_VERSION_CHANGE_HISTORY: VersionChangeHistory[] = [
  {
    id: 'vch-1',
    plateId: 'plate-1',
    versionId: 'version-1',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-01-15T10:00:00Z',
    description: '创建初始扫描版本',
  },
  {
    id: 'vch-2',
    plateId: 'plate-1',
    versionId: 'version-2',
    action: 'create',
    userId: 'user-4',
    userName: '赵标注',
    timestamp: '2024-03-15T14:30:00Z',
    description: '创建二次扫描版本',
  },
  {
    id: 'vch-3',
    plateId: 'plate-1',
    versionId: 'version-1',
    action: 'compare',
    userId: 'user-2',
    userName: '李复核',
    timestamp: '2024-03-16T09:00:00Z',
    description: '与 version-2 版本进行比对',
    details: { compareVersionId: 'version-2', diffCount: 6 },
  },
  {
    id: 'vch-4',
    plateId: 'plate-1',
    versionId: 'version-3',
    action: 'create',
    userId: 'user-1',
    userName: '张标注',
    timestamp: '2024-06-20T09:00:00Z',
    description: '创建高清重扫版本',
  },
];

const MOCK_FINAL_CONCLUSIONS: FinalConclusion[] = [
  {
    id: 'conclusion-1',
    plateId: 'plate-1',
    versionIds: ['version-1', 'version-2'],
    title: '猎户座天区底片 V1-V2 比对结论',
    content:
      '经过两个版本的详细比对，共发现 6 处差异。其中新增缺陷 1 处（扫描条纹），消失缺陷 0 处，位置偏移 2 处，类型变更 0 处，无变化 3 处。\n\n主要变化：\n1. 中央霉斑区域略有扩大，建议加强防霉处理\n2. 新增扫描条纹缺陷需通过频域滤波去除\n3. 亮点污染经确认为真实星体，已驳回标注\n\n整体而言，底片保存状况良好，主要差异来自扫描精度和标注标准的不同。',
    status: 'archived',
    createdBy: 'user-2',
    createdByName: '李复核',
    createdAt: '2024-03-20T15:00:00Z',
    updatedAt: '2024-03-25T10:00:00Z',
    reviewerIds: ['user-2', 'user-5'],
    reviewerNames: ['李复核', '陈研究员'],
    approvedCount: 2,
    totalReviewers: 2,
  },
];

const MOCK_TREND_STATISTICS: TrendStatistics[] = [
  {
    date: '2024-01',
    totalDefects: 4,
    addedDefects: 4,
    removedDefects: 0,
    byType: { scratch: 2, mold: 2, bright_spot: 0, scan_defect: 0 },
  },
  {
    date: '2024-02',
    totalDefects: 6,
    addedDefects: 2,
    removedDefects: 0,
    byType: { scratch: 2, mold: 2, bright_spot: 1, scan_defect: 1 },
  },
  {
    date: '2024-03',
    totalDefects: 6,
    addedDefects: 1,
    removedDefects: 1,
    byType: { scratch: 2, mold: 2, bright_spot: 1, scan_defect: 1 },
  },
  {
    date: '2024-04',
    totalDefects: 5,
    addedDefects: 0,
    removedDefects: 1,
    byType: { scratch: 2, mold: 2, bright_spot: 0, scan_defect: 1 },
  },
  {
    date: '2024-05',
    totalDefects: 7,
    addedDefects: 2,
    removedDefects: 0,
    byType: { scratch: 2, mold: 3, bright_spot: 0, scan_defect: 2 },
  },
  {
    date: '2024-06',
    totalDefects: 7,
    addedDefects: 1,
    removedDefects: 1,
    byType: { scratch: 2, mold: 3, bright_spot: 0, scan_defect: 2 },
  },
];

export const initialState: State = {
  currentUser: defaultUser,
  plates: MOCK_PLATES,
  annotations: MOCK_ANNOTATIONS,
  reviewRecords: MOCK_REVIEW_RECORDS,
  history: MOCK_HISTORY,
  detectionResults: MOCK_DETECTION_RESULTS,
  modificationRecords: MOCK_MODIFICATION_RECORDS,
  selectedPlateId: MOCK_PLATES[0]?.id || null,
  selectedAnnotationId: null,
  selectedAnnotationIds: [],
  filters: DEFAULT_FILTERS,
  historyUndoStack: [],
  historyRedoStack: [],
  confidenceThreshold: 0.5,
  plateVersions: MOCK_PLATE_VERSIONS,
  versionAnnotations: MOCK_VERSION_ANNOTATIONS,
  comparisons: MOCK_COMPARISONS,
  approvalRecords: MOCK_APPROVAL_RECORDS,
  versionChangeHistory: MOCK_VERSION_CHANGE_HISTORY,
  finalConclusions: MOCK_FINAL_CONCLUSIONS,
  trendStatistics: MOCK_TREND_STATISTICS,
  selectedBaseVersionId: MOCK_PLATE_VERSIONS[0]?.id || null,
  selectedCompareVersionId: MOCK_PLATE_VERSIONS[1]?.id || null,
  selectedDiffItemId: null,
  comparisonViewMode: 'split',
  showUnchanged: true,
};

export interface State {
  currentUser: User;
  plates: Plate[];
  annotations: Annotation[];
  reviewRecords: ReviewRecord[];
  history: HistoryEntry[];
  detectionResults: DetectionResult[];
  modificationRecords: ModificationRecord[];
  selectedPlateId: string | null;
  selectedAnnotationId: string | null;
  selectedAnnotationIds: string[];
  filters: FilterOptions;
  historyUndoStack: HistoryEntry[][];
  historyRedoStack: HistoryEntry[][];
  confidenceThreshold: number;
  plateVersions: PlateVersion[];
  versionAnnotations: Record<string, Annotation[]>;
  comparisons: ComparisonResult[];
  approvalRecords: ApprovalRecord[];
  versionChangeHistory: VersionChangeHistory[];
  finalConclusions: FinalConclusion[];
  trendStatistics: TrendStatistics[];
  selectedBaseVersionId: string | null;
  selectedCompareVersionId: string | null;
  selectedDiffItemId: string | null;
  comparisonViewMode: 'split' | 'overlay';
  showUnchanged: boolean;
}
